### ISSUE TITLE
File outside of allowed directories

### ISSUE THREAD

**Issue by Thierryonre** [yuyasugano/sushi-uni-arbitrage#1]
After running npm install, I tried to run brownie compile but it resulted in:

INFO: Could not find files for the given pattern(s).
Brownie v1.13.1 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.5.17
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

node_modules/@studydefi/money-legos/dydx/contracts/DydxFlashloanBase.sol:4:1: ParserError: Source "@openzeppelin/contracts/math/SafeMath.sol" not found: File outside of allowed directories.
import "@openzeppelin/contracts/math/SafeMath.sol";
^-------------------------------------------------^

node_modules/@studydefi/money-legos/dydx/contracts/DydxFlashloanBase.sol:5:1: ParserError: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File outside of allowed directories.
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
^------------------------------------------------------^

**Comment by yuyasugano** [comment]
> After running npm install, I tried to run brownie compile but it resulted in:
> 
> INFO: Could not find files for the given pattern(s).
> Brownie v1.13.1 - Python development framework for Ethereum
> 
> Compiling contracts...
> Solc version: 0.5.17
> Optimizer: Enabled Runs: 200
> EVM Version: Istanbul
> CompilerError: solc returned the following errors:
> 
> node_modules/@studydefi/money-legos/dydx/contracts/DydxFlashloanBase.sol:4:1: ParserError: Source "@openzeppelin/contracts/math/SafeMath.sol" not found: File outside of allowed directories.
> import "@openzeppelin/contracts/math/SafeMath.sol";
> ^-------------------------------------------------^
> 
> node_modules/@studydefi/money-legos/dydx/contracts/DydxFlashloanBase.sol:5:1: ParserError: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File outside of allowed directories.
> import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
> ^------------------------------------------------------^

@Thierryonre Thanks for reporting. Please change the file imports as below in the file DydxFlashloanBase.sol.
Openzeppelin library is located in the different place.

pragma solidity ^0.5.7;
pragma experimental ABIEncoderV2;

import "../../../../@openzeppelin/contracts/math/SafeMath.sol";
import "../../../../@openzeppelin/contracts/token/ERC20/IERC20.sol";

import "./ISoloMargin.sol";

**Comment by Thierryonre** [comment]
Thanks :D
