### ISSUE TITLE
Aren't dydx loans deprecated?

### ISSUE THREAD

**Issue by cdcv** [yuyasugano/sushi-uni-arbitrage#2]
Does this code still function?
Either way, thank you for sharing it.

**Comment by yuyasugano** [comment]
@cdcv Sorry this repo hasn't been maintained. If dydx loan was depreciated, please do not use the code in this repo. As written in diaclaimer, the all codes are written for informational and educational purpose only. So please do not expect the codes can function for the current protocol and also not expect this can be profitable. Thanks for your understanding.
